import EmberRouter from '@ember/routing/router';
import config from './config/environment';

const Router = EmberRouter.extend({
  location: config.locationType,
  rootURL: config.rootURL,
});

Router.map(function() {
  this.route('test', function() {
    this.route('child', function() {});
  });

  this.route('dropzone');

  this.route('docs', function() {
    // docs homepage (required)
    this.route('components', function() {
      this.route('actions', function() {
        this.route('action-list');
      });
    });

    this.route('api', function() {
      // autogenerated API homepage (required)
      this.route('item', { path: '/*path' }); // autogenerated API subpages (required)
    });
  });

  this.route('not-found', { path: '/*path' });
});

export default Router;
